### ISSUE TITLE
Uploading images throws an error

### ISSUE THREAD

**Issue by zphang** [linuxserver/docker-hedgedoc#9]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Uploading images (i.e. pasting into the editor) seems not to work. I'm not sure if this is a configuration issue on my end.

------------------------------

## Expected Behavior

Pasting an image from a clipboard should upload a file (e.g. to the file system) that is then embedded within the markdown.

## Current Behavior

* The editor gets stuck showing `![Uploading file..._HASHHERE]()`
* Looking into the filesystem, I do see files appear in the `/config/upload` folder.
* I get the following error message in the docker log:

```
2021-03-21T03:43:40.557Z info: deserializeUser: 29e9590d-e1b1-499b-a25e-c3ddda476941
(node:260) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: /uploads/
at onParseError (internal/url.js:257:9)
at new URL (internal/url.js:333:5)
at new URL (internal/url.js:330:22)
at Object.exports.uploadImage (/opt/hedgedoc/lib/web/imageRouter/filesystem.js:28:19)
at /opt/hedgedoc/lib/web/imageRouter/index.js:63:22
(node:260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

## Steps to Reproduce

1. Create a note and paste an image from clipboard

## Environment

On Unraid.

## Command used to create docker container (run/create/compose/screenshot)

Via Unraid.

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

[4mSequelize CLI [Node: 12.21.0, CLI: 5.5.1, ORM: 5.22.3][24m

Loaded configuration file "../../config/config.json".
No migrations were executed, database schema was already up to date.
2021-03-21T04:20:41.443Z warn: Neither 'domain' nor 'CMD_DOMAIN' is configured. This can cause issues with various components.
Hint: Make sure 'protocolUseSSL' and 'urlAddPort' or 'CMD_PROTOCOL_USESSL' and 'CMD_URL_ADDPORT' are configured properly.
2021-03-21T04:20:41.445Z warn: Session secret not set. Using random generated one. Please set `sessionSecret` in your config.json file. All users will be logged out.
2021-03-21T04:20:41.872Z info: HTTP Server listening at 0.0.0.0:3000
2021-03-21T04:20:56.366Z info: 192.168.1.41 - - [21/Mar/2021:04:20:56 +0000] "GET / HTTP/1.1" 304 - "http://192.168.1.10/Docker" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:86.0) Gecko/20100101 Firefox/86.0"

2021-03-21T04:20:56.663Z info: 192.168.1.41 - - [21/Mar/2021:04:20:56 +0000] "GET /config HTTP/1.1" 304 - "http://192.168.1.10:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:86.0) Gecko/20100101 Firefox/86.0"

2021-03-21T04:20:56.731Z info: 192.168.1.41 - - [21/Mar/2021:04:20:56 +0000] "GET /me HTTP/1.1" 200 22 "http://192.168.1.10:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:86.0) Gecko/20100101 Firefox/86.0"

2021-03-21T04:20:59.643Z info: serializeUser: 29e9590d-e1b1-499b-a25e-c3ddda476941
2021-03-21T04:20:59.659Z info: 192.168.1.41 - - [21/Mar/2021:04:20:59 +0000] "POST /login HTTP/1.1" 302 46 "http://192.168.1.10:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:86.0) Gecko/20100101 Firefox/86.0"

2021-03-21T04:20:59.956Z info: 192.168.1.41 - - [21/Mar/2021:04:20:59 +0000] "GET / HTTP/1.1" 200 - "http://192.168.1.10:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:86.0) Gecko/20100101 Firefox/86.0"

2021-03-21T04:20:59.984Z info: deserializeUser: 29e9590d-e1b1-499b-a25e-c3ddda476941
2021-03-21T04:20:59.987Z info: 192.168.1.41 - - [21/Mar/2021:04:20:59 +0000] "GET /config HTTP/1.1" 304 - "http://192.168.1.10:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:86.0) Gecko/20100101 Firefox/86.0"

2021-03-21T04:21:00.135Z info: deserializeUser: 29e9590d-e1b1-499b-a25e-c3ddda476941
2021-03-21T04:21:00.288Z info: 192.168.1.41 - - [21/Mar/2021:04:21:00 +0000] "GET /me HTTP/1.1" 200 156 "http://192.168.1.10:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:86.0) Gecko/20100101 Firefox/86.0"

2021-03-21T04:21:00.709Z info: deserializeUser: 29e9590d-e1b1-499b-a25e-c3ddda476941
2021-03-21T04:21:00.715Z info: 192.168.1.41 - - [21/Mar/2021:04:21:00 +0000] "GET /history HTTP/1.1" 200 88 "http://192.168.1.10:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:86.0) Gecko/20100101 Firefox/86.0"

2021-03-21T04:21:02.257Z info: deserializeUser: 29e9590d-e1b1-499b-a25e-c3ddda476941
2021-03-21T04:21:02.401Z info: 192.168.1.41 - - [21/Mar/2021:04:21:02 +0000] "GET /q2_2SPJITfinBjEaNpkSzA HTTP/1.1" 304 - "http://192.168.1.10:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:86.0) Gecko/20100101 Firefox/86.0"

2021-03-21T04:21:02.483Z info: deserializeUser: 29e9590d-e1b1-499b-a25e-c3ddda476941
2021-03-21T04:21:02.486Z info: 192.168.1.41 - - [21/Mar/2021:04:21:02 +0000] "GET /config HTTP/1.1" 304 - "http://192.168.1.10:3000/q2_2SPJITfinBjEaNpkSzA" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:86.0) Gecko/20100101 Firefox/86.0"

2021-03-21T04:21:04.806Z info: deserializeUser: 29e9590d-e1b1-499b-a25e-c3ddda476941
2021-03-21T04:21:05.632Z info: deserializeUser: 29e9590d-e1b1-499b-a25e-c3ddda476941
2021-03-21T04:21:05.802Z info: 192.168.1.41 - - [21/Mar/2021:04:21:05 +0000] "GET /me HTTP/1.1" 304 - "http://192.168.1.10:3000/q2_2SPJITfinBjEaNpkSzA" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:86.0) Gecko/20100101 Firefox/86.0"

2021-03-21T04:21:05.632Z info: deserializeUser: 29e9590d-e1b1-499b-a25e-c3ddda476941
2021-03-21T04:21:05.802Z info: 192.168.1.41 - - [21/Mar/2021:04:21:05 +0000] "GET /me HTTP/1.1" 304 - "http://192.168.1.10:3000/q2_2SPJITfinBjEaNpkSzA" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:86.0) Gecko/20100101 Firefox/86.0"

2021-03-21T04:21:12.214Z info: deserializeUser: 29e9590d-e1b1-499b-a25e-c3ddda476941
(node:261) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: /uploads/
at onParseError (internal/url.js:257:9)
at new URL (internal/url.js:333:5)
at new URL (internal/url.js:330:22)
at Object.exports.uploadImage (/opt/hedgedoc/lib/web/imageRouter/filesystem.js:28:19)
at /opt/hedgedoc/lib/web/imageRouter/index.js:63:22
(node:261) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:261) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-03-21T04:21:12.214Z info: deserializeUser: 29e9590d-e1b1-499b-a25e-c3ddda476941
(node:261) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: /uploads/
at onParseError (internal/url.js:257:9)
at new URL (internal/url.js:333:5)
at new URL (internal/url.js:330:22)
at Object.exports.uploadImage (/opt/hedgedoc/lib/web/imageRouter/filesystem.js:28:19)
at /opt/hedgedoc/lib/web/imageRouter/index.js:63:22
(node:261) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:261) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Additional Notes

I noticed an warning regarding `domain`/`CMD_DOMAIN` not being set. Some googling seemed to indicate that this may be related to the problem. However, I've tried modifying the `config.json` with both `domain` and `CMD_DOMAIN` keys and neither seems to be picked up.

**Comment by aptalca** [comment]
This sounds like a hedgedoc issue rather than a docker one. Please report it upstream to them.

**Comment by zphang** [comment]
You're probably right. For what it's worth, I was able to hack it into working by nesting the needed keys within an environment in `config.json`, e.g.:

```json
{
  "production": {
    "use_env_variable": "CMD_DB_URL",
    "domain": "mydomainhere.com"
  }
}
```

I'm not familiar enough with either HedgeDoc/node or docker to determine where a fix should go, but maybe this will be helpful for someone.
